#After sorting the dataset with pandas I am using this file to create a little piece of code that saves an histogram of each variable to png
# I keep using this source as reference: https://medium.com/codebagng/basic-analysis-of-the-iris-data-set-using-python-2995618a6342
#More References: https://realpython.com/courses/numpy-arange/
#Took as reference in how to work with CSV files:https://realpython.com/python-csv/

import pandas as pd #Imported pandas library in order to organise the data .
import matplotlib.pyplot as plt #Imported matplot library to create plots.
import numpy as np
# We read CSV file with pandas library .
df= pd.read_csv('irisdatasetmod.csv')#,index_col='Species') #Added Species column as index column instead of the one generated by the system by default. 
#print (df)
#now the column "Species" is the index , then we need to save this modified CSV.


#df = pd.read_csv('irisdataset.csv', 
            #index_col='Species', 
            #header=0, 
            #names=['Species','SepalLength','SepalWidth','PetalLength','PetalWidth'])
#df.to_csv('irisdatasetmod.csv')


#Now in order to show this data in a scatter plot we do the following:
#I create variables to extract the data from the file. 
sepw= df['SepalWidth']
sepl= df['SepalLength']


#Now I create an empty list and with list function convert the dataset content into a Python list that we can use to
#create the scatterplot.
x=[]
y=[]

x=list(sepw)
y=list(sepl)


plt.scatter(x,y)
plt.xlabel('Sepal Length')
plt.ylabel('Sepal Width')
plt.title('Correlation between sepal lentgh and sepal width for iris flowers')


plt.legend()
plt.show()















